---
title: 'Lessons from grading graduate work as an undergrad'
author: Derek Borders
date: '2022-02-10'
slug: grading-lessons-01
categories: []
tags: []
---

# Intro  

Through a short series of bureaucratic happenstances, I find myself grading for a graduate-level machine learning course as an undergraduate. I excelled at my undergraduate machine learning, and the curriculum is essentially the same. Nonetheless, I expect some interesting tidbits may be gleaned from the experience.

# Part 1

## Technical Stuff

In my first grading experience for the course, I have already learned or re-learned a few interesting things of a technical nature. 

### Quicksort3  

I have spent my fair share of time with algorithms both in class and recreationally going down rabbit holes. I don't know how I didn't come across [Quicksort3](https://www.geeksforgeeks.org/3-way-quicksort-dutch-national-flag/) before. Perhaps I just forgot it. It is certainly the way I am naturally inclined to handle duplicate values in a Quicksort scenario.

The basic concept of Quicksort3 is to keep a third 'middle' list of values equal to the pivot, and only call the recursion with the values strictly less than or greater than the pivot. 


### Median of 3  
[Median of 3](https://www.cs.cornell.edu/courses/JavaAndDS/files/sort3Quicksort3.pdf)^[This link is a nice encapsulation of some basic Quicksort optimizations, including Median of 3.] is another instance of something I wanted to exist but hadn't found (or had somehow forgotten). When I first encountered Quicksort (the first several times, in fact) I had to struggle to resist the urge to ruin the runtime complexity by hunting down the median at each stage of the recursion. Eventually I accepted that despite my distaste for using randomness in this type of situation, somebody else had proven and tested that randomness better than finding the median or picking the first, last, or middle element.

It never occurred to me that the median could be roughly approximated to a useful extent by taking the median of the first, last, and center elements. This requires negligible overhead and apparently has been proven to be substantially faster on average than using a random pivot. 


### Python's List Comprehension
I re-learned how Python's [list comprehension](https://www.w3schools.com/python/python_lists_comprehension.asp) works. I've never used it enough to form a lasting habit. Hopefully it'll stick this time.  

As a reminder for anybody else in the same boat, Python's list comprehension turns several lines of loop: 

```{eval=F, echo=T}
for item in list:
  if a: 
    b(item)
  else: 
    c(item)
```

into a clean, readable (if you keep it simple) one liner:

```{eval=F, echo=T}
[b(item) for item in list if a else c(item)]
```

Obviously, this can quickly get out of hand and lead to 'clever' code that is impossible to read. Still, this is a tool I could safely use more in my own code.


### Python Swaps
I learned that swaps in python are as easy as `a,b = b,a` and apparently it's [more efficient](https://betterprogramming.pub/you-didnt-truly-understand-the-infamous-python-trick-a-b-b-a-2e4e8634f5a9) under the hood than I ever would have assumed.



## Observations  

I was pleased and impressed, but not particularly surprised, at the overall higher quality of the submissions I was grading compared to the grading I've done for undergraduates before. Honestly, these were the caliber of submissions I expected to be standard for undergrads when I transferred to a proper university from community college.

It's nice to see a class full of people who overhwelmingly deliver on not only the basic requirements of their assignments, but almost universally opted to include the suggested bonus features.

